"""
تولید گزارش HTML
"""

from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime


class HTMLReporter:
    """تولید گزارش HTML"""
    
    def __init__(self, output_dir: str = 'reports'):
        """
        Args:
            output_dir: پوشه ذخیره گزارش‌ها
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(self,
                       training_analysis: Optional[Dict] = None,
                       evaluation_results: Optional[Dict] = None,
                       action_analysis: Optional[Dict] = None,
                       comparison_results: Optional[Dict] = None,
                       plot_paths: Optional[Dict] = None,
                       save_name: str = "analysis_report"):
        """
        تولید گزارش HTML کامل
        
        Args:
            training_analysis: نتایج تحلیل آموزش
            evaluation_results: نتایج ارزیابی مدل
            action_analysis: تحلیل اکشن‌ها
            comparison_results: نتایج مقایسه
            plot_paths: مسیرهای نمودارها
            save_name: نام فایل گزارش
        """
        html_content = self._generate_html(
            training_analysis, evaluation_results, action_analysis,
            comparison_results, plot_paths
        )
        
        report_path = self.output_dir / f"{save_name}.html"
        report_path.write_text(html_content, encoding='utf-8')
        
        print(f"✅ HTML report generated: {report_path}")
        return report_path
    
    def _generate_html(self, training_analysis, evaluation_results, 
                      action_analysis, comparison_results, plot_paths):
        """تولید محتوای HTML"""
        
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MADDPG Analysis Report</title>
    <style>
        {self._get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🚁 MADDPG UAV Offloading Analysis Report</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </header>
        
        {self._generate_summary_section(training_analysis, evaluation_results)}
        {self._generate_training_section(training_analysis, plot_paths)}
        {self._generate_evaluation_section(evaluation_results, plot_paths)}
        {self._generate_action_section(action_analysis, plot_paths)}
        {self._generate_comparison_section(comparison_results, plot_paths)}
        
        <footer>
            <p>Report generated by Analysis Toolkit v1.0</p>
        </footer>
    </div>
</body>
</html>
"""
        return html
    
    def _get_css(self):
        """استایل CSS"""
        return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        
        header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
        }
        
        header h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        
        .timestamp {
            font-size: 0.9em;
            opacity: 0.9;
        }
        
        section {
            padding: 30px;
            border-bottom: 2px solid #f0f0f0;
        }
        
        section:last-of-type {
            border-bottom: none;
        }
        
        h2 {
            color: #667eea;
            font-size: 1.8em;
            margin-bottom: 20px;
            border-left: 5px solid #667eea;
            padding-left: 15px;
        }
        
        h3 {
            color: #764ba2;
            font-size: 1.3em;
            margin-top: 20px;
            margin-bottom: 15px;
        }
        
        .metric-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin: 20px 0;
        }
        
        .metric-card {
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            text-align: center;
        }
        
        .metric-card .label {
            font-size: 0.9em;
            color: #666;
            margin-bottom: 5px;
        }
        
        .metric-card .value {
            font-size: 1.8em;
            font-weight: bold;
            color: #667eea;
        }
        
        .plot-container {
            margin: 20px 0;
            text-align: center;
        }
        
        .plot-container img {
            max-width: 100%;
            border-radius: 8px;
            box-shadow: 0 4px 10px rgba(0,0,0,0.1);
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        
        th {
            background-color: #667eea;
            color: white;
            font-weight: bold;
        }
        
        tr:hover {
            background-color: #f5f5f5;
        }
        
        .status-badge {
            display: inline-block;
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.9em;
            font-weight: bold;
        }
        
        .status-converged {
            background-color: #4CAF50;
            color: white;
        }
        
        .status-training {
            background-color: #FF9800;
            color: white;
        }
        
        footer {
            background-color: #f8f9fa;
            text-align: center;
            padding: 20px;
            color: #666;
        }
        """
    
    def _generate_summary_section(self, training_analysis, evaluation_results):
        """بخش خلاصه"""
        if not training_analysis and not evaluation_results:
            return ""
        
        html = '<section id="summary"><h2>📊 Executive Summary</h2>'
        
        if training_analysis:
            trend = training_analysis.get('trend_analysis', {})
            html += f"""
            <div class="metric-grid">
                <div class="metric-card">
                    <div class="label">Training Episodes</div>
                    <div class="value">{training_analysis.get('total_episodes', 'N/A')}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Final Reward</div>
                    <div class="value">{trend.get('final_reward', 0):.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Best Reward</div>
                    <div class="value">{trend.get('best_reward', 0):.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Improvement</div>
                    <div class="value">{trend.get('improvement_percent', 0):.1f}%</div>
                </div>
            </div>
            """
        
        if evaluation_results:
            stats = evaluation_results.get('statistics', {})
            html += f"""
            <h3>🎯 Model Performance</h3>
            <div class="metric-grid">
                <div class="metric-card">
                    <div class="label">Mean Reward</div>
                    <div class="value">{stats.get('mean_reward', 0):.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Std Deviation</div>
                    <div class="value">{stats.get('std_reward', 0):.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Max Reward</div>
                    <div class="value">{stats.get('max_reward', 0):.2f}</div>
                </div>
                <div class="metric-card">
                    <div class="label">Min Reward</div>
                    <div class="value">{stats.get('min_reward', 0):.2f}</div>
                </div>
            </div>
            """
        
        html += '</section>'
        return html
    
    def _generate_training_section(self, training_analysis, plot_paths):
        """بخش آموزش"""
        if not training_analysis:
            return ""
        
        html = '<section id="training"><h2>📈 Training Analysis</h2>'
        
        # Convergence status
        conv = training_analysis.get('convergence', {})
        if conv.get('converged'):
            status_class = 'status-converged'
            status_text = 'Converged'
        else:
            status_class = 'status-training'
            status_text = 'In Progress'
        
        html += f'<p>Status: <span class="status-badge {status_class}">{status_text}</span></p>'
        
        if conv.get('converged'):
            html += f'<p>Convergence Point: Episode {conv.get("convergence_episode", "N/A")}</p>'
        
        # Training phases
        phases = training_analysis.get('phases', {})
        if phases:
            html += '<h3>Training Phases</h3><table><thead><tr><th>Phase</th><th>Mean Reward</th><th>Std</th></tr></thead><tbody>'
            for phase_name, phase_data in phases.items():
                html += f"""
                <tr>
                    <td>{phase_name.replace('_', ' ').title()}</td>
                    <td>{phase_data.get('mean', 0):.2f}</td>
                    <td>{phase_data.get('std', 0):.2f}</td>
                </tr>
                """
            html += '</tbody></table>'
        
        # Training plot
        if plot_paths and 'training_curve' in plot_paths:
            html += f'<div class="plot-container"><img src="{plot_paths["training_curve"]}" alt="Training Curve"></div>'
        
        html += '</section>'
        return html
    
    def _generate_evaluation_section(self, evaluation_results, plot_paths):
        """بخش ارزیابی"""
        if not evaluation_results:
            return ""
        
        html = '<section id="evaluation"><h2>🎯 Model Evaluation</h2>'
        
        # Reward distribution plot
        if plot_paths and 'reward_distribution' in plot_paths:
            html += f'<div class="plot-container"><img src="{plot_paths["reward_distribution"]}" alt="Reward Distribution"></div>'
        
        html += '</section>'
        return html
    
    def _generate_action_section(self, action_analysis, plot_paths):
        """بخش اکشن‌ها"""
        if not action_analysis:
            return ""
        
        html = '<section id="actions"><h2>🎮 Action Analysis</h2>'
        
        # Offload distribution
        offload = action_analysis.get('offload_distribution', {})
        if offload:
            html += '<h3>Offload Distribution</h3><table><thead><tr><th>Location</th><th>Percentage</th><th>Count</th></tr></thead><tbody>'
            for loc, pct in offload.get('percentages', {}).items():
                count = offload.get('counts', {}).get(loc, 0)
                html += f'<tr><td>{loc}</td><td>{pct:.1f}%</td><td>{count}</td></tr>'
            html += '</tbody></table>'
        
        # Action plots
        if plot_paths:
            if 'offload_distribution' in plot_paths:
                html += f'<div class="plot-container"><img src="{plot_paths["offload_distribution"]}" alt="Offload Distribution"></div>'
            if 'resource_allocation' in plot_paths:
                html += f'<div class="plot-container"><img src="{plot_paths["resource_allocation"]}" alt="Resource Allocation"></div>'
            if 'movement_pattern' in plot_paths:
                html += f'<div class="plot-container"><img src="{plot_paths["movement_pattern"]}" alt="Movement Pattern"></div>'
        
        html += '</section>'
        return html
    
    def _generate_comparison_section(self, comparison_results, plot_paths):
        """بخش مقایسه"""
        if not comparison_results:
            return ""
        
        html = '<section id="comparison"><h2>⚖️ Model Comparison</h2>'
        
        # Ranking table
        ranking = comparison_results.get('ranking', [])
        if ranking:
            html += '<h3>Performance Ranking</h3><table><thead><tr><th>Rank</th><th>Model</th><th>Mean Reward</th><th>Std</th></tr></thead><tbody>'
            for rank, model_info in enumerate(ranking, 1):
                html += f"""
                <tr>
                    <td>{rank}</td>
                    <td>{model_info['model']}</td>
                    <td>{model_info['mean_reward']:.2f}</td>
                    <td>{model_info['std_reward']:.2f}</td>
                </tr>
                """
            html += '</tbody></table>'
        
        # Comparison plot
        if plot_paths and 'comparison' in plot_paths:
            html += f'<div class="plot-container"><img src="{plot_paths["comparison"]}" alt="Model Comparison"></div>'
        
        html += '</section>'
        return html
